/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EJU06;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jdavid
 */
public class GUI extends javax.swing.JFrame {

  /**
   * Creates new form GUI
   */
  public GUI() {
    initComponents();

    //Permite centrar la aplicación en el centro de la pantalla
    this.setLocationRelativeTo(null);

  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    btnModificar = new javax.swing.JButton();
    btnAgregar = new javax.swing.JButton();
    btnEliminar = new javax.swing.JButton();
    txtTitulo = new javax.swing.JTextField();
    txtAutor = new javax.swing.JTextField();
    txtYear = new javax.swing.JTextField();
    txtGenero = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    txtId = new javax.swing.JTextField();
    txtObtenerLibros = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    pantalla = new javax.swing.JTable();
    jLabel7 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("CRUD Administrador De Libros - Juan David Ramirez");

    jPanel1.setBackground(new java.awt.Color(0, 51, 51));

    jLabel1.setBackground(new java.awt.Color(255, 255, 255));
    jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("ADMINISTRADOR DE LIBROS");

    jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Titulo");

    jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Autor ");

    jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("Genero");

    jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("Año");

    btnModificar.setBackground(new java.awt.Color(0, 51, 51));
    btnModificar.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
    btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EJU06/icons/deberes.png"))); // NOI18N
    btnModificar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnModificarActionPerformed(evt);
      }
    });

    btnAgregar.setBackground(new java.awt.Color(0, 51, 51));
    btnAgregar.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
    btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
    btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EJU06/icons/addLibro.png"))); // NOI18N
    btnAgregar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAgregarActionPerformed(evt);
      }
    });

    btnEliminar.setBackground(new java.awt.Color(0, 51, 51));
    btnEliminar.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
    btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EJU06/icons/borrar (1).png"))); // NOI18N
    btnEliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEliminarActionPerformed(evt);
      }
    });

    txtTitulo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

    txtAutor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

    txtYear.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

    txtGenero.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

    jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("ISBN");

    txtId.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

    txtObtenerLibros.setBackground(new java.awt.Color(0, 0, 153));
    txtObtenerLibros.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
    txtObtenerLibros.setForeground(new java.awt.Color(255, 255, 255));
    txtObtenerLibros.setText("Obtener Libros");
    txtObtenerLibros.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtObtenerLibrosActionPerformed(evt);
      }
    });

    pantalla.setAutoCreateRowSorter(true);
    pantalla.setBackground(new java.awt.Color(255, 255, 255));
    pantalla.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
    pantalla.setForeground(new java.awt.Color(0, 0, 0));
    pantalla.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null}
      },
      new String [] {
        "ISBN", "Titulo", "Autor", "Año", "Genero"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    pantalla.setSelectionBackground(new java.awt.Color(255, 255, 255));
    pantalla.setShowGrid(true);
    jScrollPane2.setViewportView(pantalla);

    jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel7.setText("Editar");

    jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(255, 255, 255));
    jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel9.setText("Agregar");

    jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel8.setText("Eliminar");

    jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EJU06/icons/libro2.png"))); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(60, Short.MAX_VALUE)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(58, 58, 58))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(104, 104, 104)
        .addComponent(txtObtenerLibros)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(103, 103, 103))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(116, 116, 116)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(159, 159, 159)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(158, 158, 158)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel8))
                  .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addGap(18, 18, 18)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jLabel3)
                      .addComponent(jLabel5))
                    .addGap(21, 21, 21)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel6)
              .addComponent(jLabel2))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(237, 237, 237)
        .addComponent(jLabel1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(36, 36, 36)
        .addComponent(jLabel1)
        .addGap(5, 5, 5)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtObtenerLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(33, 33, 33)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(32, 32, 32)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addGap(65, 65, 65)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnModificar)
                .addGap(0, 0, Short.MAX_VALUE))
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregar)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel7)
              .addComponent(jLabel9))
            .addGap(316, 316, 316))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(btnEliminar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel8)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

    // 1. Obtener los datos del formulario
    String idLibro = txtId.getText();
    String titulo = txtTitulo.getText();
    String autor = txtAutor.getText();
    String year = txtYear.getText();
    String genero = txtGenero.getText();

    // 2. Conectar a la base de datos y realizar la inserción
    Connection conn = null;
    PreparedStatement pst = null;

    try {
      // 3. Establecer la conexión (asegúrate de que tu Driver JDBC esté configurado correctamente)
      conn = (Connection) ConexionDB.obtenerConexion();

      // 4. Preparar la consulta SQL
      String sql = "INSERT INTO Libro(idLibro, titulo, autor, año, genero) VALUES (?, ?, ?, ?, ?)";
      pst = conn.prepareStatement(sql);

      // 5. Establecer los valores de los parámetros
      pst.setString(1, idLibro);
      pst.setString(2, titulo);
      pst.setString(3, autor);
      pst.setString(4, year);
      pst.setString(5, genero);

      // 6. Ejecutar la consulta de inserción
      int filasAfectadas = pst.executeUpdate();

      if (filasAfectadas > 0) {
        JOptionPane.showMessageDialog(this, "¡Datos agregados correctamente!");

        //Limpiar datos del formulario, una vez se agregen a la base de datos
        txtId.setText("");
        txtTitulo.setText("");
        txtAutor.setText("");
        txtYear.setText("");
        txtGenero.setText("");
      } else {
        JOptionPane.showMessageDialog(this, "Hubo un problema al agregar los datos.");
      }
    } catch (SQLException e) {
      // Manejar errores
      JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage());
    } finally {
      try {
        // Cerrar los recursos
        if (pst != null) {
          pst.close();
        }
        if (conn != null) {
          conn.close();
        }
      } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cerrar los recursos: " + e.getMessage());
      }
    }
  }//GEN-LAST:event_btnAgregarActionPerformed

  private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

    // 1. Obtener los datos del formulario
    String idLibro = txtId.getText();
    String titulo = txtTitulo.getText().isEmpty() ? null : txtTitulo.getText();
    String autor = txtAutor.getText().isEmpty() ? null : txtAutor.getText();
    String year = txtYear.getText().isEmpty() ? null : txtYear.getText();
    String genero = txtGenero.getText().isEmpty() ? null : txtGenero.getText();

    // 2. Conectar a la base de datos y realizar la inserción
    Connection conn = null;
    PreparedStatement stmt = null;

    try {
      // 3. Establecer la conexión (asegúrate de que tu Driver JDBC esté configurado correctamente)
      conn = (Connection) ConexionDB.obtenerConexion();

      // 4. Preparar la consulta SQL
      String sql = "UPDATE Libro SET " + "titulo = CASE WHEN ? IS NOT NULL THEN ? ELSE titulo END, "
              + "autor = CASE WHEN ? IS NOT NULL THEN ? ELSE autor END, "
              + "año = CASE WHEN ? IS NOT NULL THEN ? ELSE año END, "
              + "genero = CASE WHEN ? IS NOT NULL THEN ? ELSE genero END "
              + "WHERE idLibro = ?";

      stmt = conn.prepareStatement(sql);

      // 5. Establecer los valores de los parámetros
      // Establecer los valores para cada columna
      stmt.setObject(1, titulo);  // Si newTitulo es null, no se actualizará
      stmt.setObject(2, titulo);

      stmt.setObject(3, autor);    // Lo mismo para autor
      stmt.setObject(4, autor);

      stmt.setObject(5, year);  // Para año, si newAño es null no se actualizará
      stmt.setObject(6, year);

      stmt.setObject(7, genero);  // Para genero
      stmt.setObject(8, genero);

      stmt.setObject(9, idLibro);  // El idLibro para el filtro

      // 6. Ejecutar la consulta de inserción
      int filasAfectadas = stmt.executeUpdate();

      if (filasAfectadas > 0) {
        JOptionPane.showMessageDialog(this, "¡Datos actualizados correctamente!");

        //Limpiar datos del formulario, una vez se agregen a la base de datos
        txtId.setText("");
        txtTitulo.setText("");
        txtAutor.setText("");
        txtYear.setText("");
        txtGenero.setText("");
      } else {
        JOptionPane.showMessageDialog(this, "Hubo un problema al actualizar los datos.");
      }
    } catch (SQLException e) {
      // Manejar errores
      JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage());
    } finally {
      try {
        // Cerrar los recursos
        if (stmt != null) {
          stmt.close();
        }
        if (conn != null) {
          conn.close();
        }
      } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cerrar los recursos: " + e.getMessage());
      }
    }
  }//GEN-LAST:event_btnModificarActionPerformed

  private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    // 1. Obtener los datos del formulario
    String idLibro = txtId.getText();

    // 2. Conectar a la base de datos y realizar la inserción
    Connection conn = null;
    PreparedStatement pst = null;

    try {
      // 3. Establecer la conexión (asegúrate de que tu Driver JDBC esté configurado correctamente)
      conn = (Connection) ConexionDB.obtenerConexion();

      // 4. Preparar la consulta SQL
      String sql = "DELETE FROM Libro WHERE idLibro = ?";
      pst = conn.prepareStatement(sql);

      // 5. Establecer los valores de los parámetros
      pst.setString(1, idLibro);

      // 6. Ejecutar la consulta de inserción
      int filasAfectadas = pst.executeUpdate();

      if (filasAfectadas > 0) {
        JOptionPane.showMessageDialog(this, "El libro con Id " + idLibro + " fue eliminado correctamente.");

        //Limpiar datos del formulario, una vez se agregen a la base de datos
        txtId.setText("");
      } else {
        JOptionPane.showMessageDialog(this, "No se encontraro registros del Id " + idLibro);
      }
    } catch (SQLException e) {
      // Manejar errores
      JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage());
    } finally {
      try {
        // Cerrar los recursos
        if (pst != null) {
          pst.close();
        }
        if (conn != null) {
          conn.close();
        }
      } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cerrar los recursos: " + e.getMessage());
      }
    }
  }//GEN-LAST:event_btnEliminarActionPerformed

  private void txtObtenerLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObtenerLibrosActionPerformed

    // 2. Conectar a la base de datos y realizar la consulta
    Connection conn = null;
    PreparedStatement stmt = null;
    ResultSet rs = null; // Para almacenar los resultados de la consulta

    try {
      // 3. Establecer la conexión
      conn = ConexionDB.obtenerConexion();

      // 4. Preparar la consulta SQL (en este caso, obtener todos los registros de "Libro")
      String sql = "SELECT * FROM Libro";
      stmt = conn.prepareStatement(sql);

      // 6. Ejecutar la consulta
      rs = stmt.executeQuery(); // Usamos executeQuery() para consultas SELECT

      // 7. Obtener el modelo de la tabla existente (ya creada en NetBeans)
      DefaultTableModel model = (DefaultTableModel) pantalla.getModel();

      // Limpiar las filas anteriores de la tabla antes de agregar nuevos datos
      model.setRowCount(0);  // Esto borra todas las filas actuales de la tabla

      // 7. Verificar si hay resultados y mostrarlos en el JTextArea
      StringBuilder resultText = new StringBuilder();  // Para acumular los resultados
      while (rs.next()) { // Recorrer todas las filas del ResultSet
        String idLibro = rs.getString("idLibro");
        String titulo = rs.getString("titulo");
        String autor = rs.getString("autor");
        String año = rs.getString("año");
        String genero = rs.getString("genero");

        // Concatenar los datos de cada libro al StringBuilder
        resultText.append("ID: ").append(idLibro)
                .append("\nTitulo: ").append(titulo)
                .append("\nAutor: ").append(autor)
                .append("\nAño: ").append(año)
                .append("\nGenero: ").append(genero)
                .append("\n\n"); // Separador entre libros
        
        // Mostrar los resultados concatenados en un JOptionPane
        model.addRow(new Object[]{idLibro, titulo, autor, año, genero});
      }

      // Si se encontraron registros, mostrar los resultados
      if (resultText.length() > 0) {
        //JOptionPane.showMessageDialog(this, resultText.toString());
      } else {
        JOptionPane.showMessageDialog(this, "No se encontraron libros.");
      }

    } catch (SQLException e) {
      // Manejar errores de la base de datos
      JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage());
    } finally {
      try {
        // Cerrar los recursos
        if (rs != null) {
          rs.close();
        }
        if (stmt != null) {
          stmt.close();
        }
        if (conn != null) {
          conn.close();
        }
      } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cerrar los recursos: " + e.getMessage());
      }
    }

  }//GEN-LAST:event_txtObtenerLibrosActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new GUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAgregar;
  private javax.swing.JButton btnEliminar;
  private javax.swing.JButton btnModificar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable pantalla;
  private javax.swing.JTextField txtAutor;
  private javax.swing.JTextField txtGenero;
  private javax.swing.JTextField txtId;
  private javax.swing.JButton txtObtenerLibros;
  private javax.swing.JTextField txtTitulo;
  private javax.swing.JTextField txtYear;
  // End of variables declaration//GEN-END:variables
}
